### PR TITLE
Feat 6.1 ethan requestflow

### PR DESCRIPTION
**Pull request by ethanstrominger**
## Description
More refactoring

These items from last pull request are still pending, will do these as separate pull requests

- You need to also remove the observeOpenRequests function and it's associated functions.
- You also need to redirect users to either request list or to offer list in the timeline module once the user performs an action, in the place of the previous redirect to finished and archived requests.
- You also need to add the links to these pages in the sidemenu's menuItems in module definition

## Release Checklist

- [ ] This code has unit tests
- [ ] I have a plan to verify that these changes are working as expected after deploy
- [ ] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected

## Security Checklist

This PR creates, modifies, or deletes:

- [ ] API routes: API routes, parameters, or user authorization
- [ ] Authentication: Authentication mechanism
- [ ] Credentials: Server side credentials, or secrets in configuration / source code
- [ ] Cryptography: Encryption, hashing, certificates, signatures, random numbers, etc.
- [ ] User data: personal information handling, logs, error messages, etc.

### CODE REVIEW

**Review by ashwinkjoseph — COMMENTED** [review]
This is good, it avoids code duplication between the containers for getting data for `My Requests` Tab and `My Offers` Tab.

I can approve these changes as I don't see anything wrong with it. But I want to know your thoughts on this -
Should we allow for code duplication here to simplify things? Maybe we can prevent code duplication by using some sort of a helper file which would have common logic?

The reason why I think it would be good to have them in separate containers is because we need to fetch data with two different filters in each of these cases - 
in My Requests you'd have - 1. Posts you created requesting help 2. Posts for which you requested help
in My Offers you'd have - 1. Posts you created offering help 2. Posts for which you offered help.

We can decrease duplicate code with helper functions which we call from each container and each container would have clearer responsibilities.

If we combine the two together, I fear that there could be a lot of `if` conditions and conditional logic in the file which would be okay now but could end up very confusing in the future as we add functionality.

This is, however, a discussion, and I can approve these changes and merge it. Just want to know your opinion of the above concerns and solution before I do so.

**Comment by ethanstrominger** [comment]
This would be a good refactoring to consider.  Can you make an issue for that and approve the pull request?

**Comment by ashwinkjoseph** [comment]
> This would be a good refactoring to consider. Can you make an issue for that and approve the pull request? @ashwinkjoseph

Hey @ethanstrominger , I think this PR introduces this issue, and it is also part of solving the issue that this PR solves. So, I am not sure if we should create a new issue for it.
Could you look into fixing the issue within this PR? I can fix it too in this PR, but I wanted to get a confirmation from you for this approach.

I can, however, merge this PR and you can introduce this change in a new PR if that is what you want

**Comment by ashwinkjoseph** [comment]
@ethanstrominger I am starting with these changes right now and would also be fixing these merge conflicts

**Comment by ashwinkjoseph** [comment]
> @ethanstrominger I am starting with these changes right now and would also be fixing these merge conflicts

@ethanstrominger Let me know if this is alright with you or if you would like to do it yourself, I will wait for your confirmation.

**Comment by ashwinkjoseph** [comment]
I have 
1. Resolved the merge conflicts with `development` branch
2. Changed name of RequestRouting file to `routes.tsx`
3. Moved tabbed logic into `routes.tsx` along with usage of generic tabs component and definition
4. Removed unecessarily created new files such as `}` and another such file

But I have left the issue presented above untouched and you can fix that or you can let me know if it is alright for me to fix it

**Review by ashwinkjoseph — APPROVED** [review]
We are going to do the changes as another PR

**Comment by schowdhury8** [comment]
@all-contributors please add @ethanstrominger for code and ideas

**Pull request merged**
