### PR TITLE
feat: add change language in sidebar and update translation json files

### PR DESCRIPTION
**Pull request by ansh-saini**
## Description
Add a dropdrown for change language in sidebar as requested in #1005 

## Motivation
Hacktoberfest 2020

## Release Checklist

- [ ] This code has unit tests
- [ ] I have a plan to verify that these changes are working as expected after deploy
- [ ] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected

## Security Checklist

This PR creates, modifies, or deletes:

- [ ] API routes: API routes, parameters, or user authorization
- [ ] Authentication: Authentication mechanism
- [ ] Credentials: Server side credentials, or secrets in configuration / source code
- [ ] Cryptography: Encryption, hashing, certificates, signatures, random numbers, etc.
- [ ] User data: personal information handling, logs, error messages, etc.

### CODE REVIEW

**Comment by schowdhury8** [comment]
@ethanstrominger why was this closed before merging?

**Comment by ashwinkjoseph** [comment]
@ethanstrominger there were a few more improvements I would have liked @ansh-saini to make here but overall it looked all right.
I don't think we should close PRs without appropriate reason and explaining it. We should also try to request changes and get a PR fixed rather than closing it. We should resort to closing only if the PR is not relevant to us.
I am re-opening this PR, please mention the reason why this has to be closed

**Review by ashwinkjoseph — APPROVED** [review]
LGTM!,
@ansh-saini you only had to change the language in English translation file, we had a tool that would automatically fill it in for the other languages.
I guess this is what you were asking for in slack, sorry misunderstood you then.

**Comment by ashwinkjoseph** [comment]
@ethanstrominger I am not merging it now, have a look at it and let me know if it can be merged or not.

**Comment by ethanstrominger** [comment]
@ashwinkjoseph I closed it by mistake.

**Comment by ashwinkjoseph** [comment]
alright, I've merged it

**Comment by ansh-saini** [comment]
Thank you 😄

**Comment by ansh-saini** [comment]
@ethanstrominger Can you please add the `hacktoberfest-accepted` label to this PR?

**Comment by ethanstrominger** [comment]
@ansh-saini I applied the hacktoberfest-accepted label.

**Comment by schowdhury8** [comment]
Thanks for the help Ansh! @all-contributors please add @ansh-saini for code

**Pull request merged**
