### PR TITLE
[ETHAN WAITING FOR WARIS TO CONFIRM MERGE OF CONFLICTS] header redesign

### PR DESCRIPTION
**Pull request by leadersheir**
## Description
Global Header redesigned according to the new landing page design. Needs minor bug fixes, no breaking code.
## Release Checklist

- [ ] This code has unit tests
- [ ] I have a plan to verify that these changes are working as expected after deploy
- [ ] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected

## Security Checklist

This PR creates, modifies, or deletes:

- [ ] API routes: API routes, parameters, or user authorization
- [ ] Authentication: Authentication mechanism
- [ ] Credentials: Server side credentials, or secrets in configuration / source code
- [ ] Cryptography: Encryption, hashing, certificates, signatures, random numbers, etc.
- [ ] User data: personal information handling, logs, error messages, etc.

### CODE REVIEW

**Comment by leadersheir** [comment]
@ashwinkjoseph Please remember to add @danainanou , @HazalYoleri , and @Cruebee to the board of contributors :v:

**Comment by schowdhury8** [comment]
> @ashwinkjoseph Please remember to add @danainanou , @HazalYoleri , and @Cruebee to the board of contributors ✌️

Absolutely! @all-contributors please add  @danainanou , @HazalYoleri , and @Cruebee for code

**Comment by schowdhury8** [comment]
[Apparently it works for only one at a time for now...](https://github.com/all-contributors/all-contributors-bot/issues/210)
@all-contributors please add @danainanou for code

**Comment by schowdhury8** [comment]
@all-contributors please add @HazalYoleri for code

**Comment by schowdhury8** [comment]
@all-contributors please add @Cruebee for code

**Review by ethanstrominger — APPROVED** [review]

**Pull request merged**
