### PR TITLE
 Feature/746 tabbed cav view

### PR DESCRIPTION
**Pull request by mcverter**
600pxMap
listView
Screenshot_2020-06-16_19-30-17

### CODE REVIEW

**Comment by mcverter** [comment]
Note:  the div that wraps the map has to have a specific pixel height.  It will not render with a height of 100%.  how do we get this right?

Also: list styles have not been approved by uiux

**Comment by sabind** [comment]
Looks really good. I love having the list and map views. It will help with accessibility as well.

**Comment by mcverter** [comment]
@sabind @ashwinkjoseph   this is ready to merge to development

**Comment by mcverter** [comment]
@sabind @ashwinkjoseph  ready to merge

**Comment by mcverter** [comment]
dev is blocked until this is merged @ashwinkjoseph

**Comment by mcverter** [comment]
@ashwinkjoseph I moved the containers back to the requests/ container but i had raised the issue before that they should be moved @sabind 
(Open|Accepted|Ongoing|Finished|Archived) Requests are all the same page -- same functionality, same code, same person.

Single Responsibility Principle for requests/ module.
"CreateRequest" and "FoundRequests" have a different purpose and structure.  They do not belong in the same module as requests/ pages

https://github.com/reach4help/reach4help/issues/747
Rename FindRequests, NewRequests to CAV_HOME and PIN_HOME #747
These two pages have nothing in common with the other pages in src/modules/requests. Rename them and possibly move to src/landingPage or src/mapView
They either belong in a home folder or a maps folder

**Comment by mcverter** [comment]
@ashwinkjoseph you broke the merge.  you need to unrevert that change

**Pull request merged**
