### PR TITLE
adding page subtitles

### PR DESCRIPTION
**Pull request by mcverter**
https://github.com/reach4help/reach4help/issues/617

More Descriptive Page Titles

### CODE REVIEW

**Comment by sabind** [comment]
This is a great start!

**Comment by sabind** [comment]
@mcverter Seems to have a conflict with some recent changes that went in.

**Comment by mcverter** [comment]
@sabind merge conflicts resolved

**Comment by mcverter** [comment]
@isma-osy this will fixed by mvp

**Pull request merged**
