### PR TITLE
feat(web-client): added loading wrapper

### LINKED ISSUE #350: Build loading wrapper
**Is your feature request related to a problem? Please describe.**
We need a loading wrapper.

**Describe the solution you'd like**
A loading wrapper that will receive children and render them according to a prop.

```
...
<LoadingWrapper loading={loading}>
    <div>content</div>
</LoadingWrapper>
```
This should be done using ant design's spinners.
https://ant.design/components/spin/

**Additional context**
This should replace, at least, the `loading`label in login.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/350)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#322 - Core Components](https://github.com/reach4help/reach4help/issues/322)

### PR DESCRIPTION
**Pull request by djohal**
## Description
Added loading wrapper to replace the default loading state

## Screenshot
loader

## Release Checklist

- [ ] This code has unit tests
- [x] I have a plan to verify that these changes are working as expected after deploy
- [x] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected

## Security Checklist

This PR creates, modifies, or deletes:

- [ ] API routes: API routes, parameters, or user authorization
- [ ] Authentication: Authentication mechanism
- [ ] Credentials: Server side credentials, or secrets in configuration / source code
- [ ] Cryptography: Encryption, hashing, certificates, signatures, random numbers, etc.
- [ ] User data: personal information handling, logs, error messages, etc.

## Additional Notes
closes #350

### CODE REVIEW

**Comment by ashwinkjoseph** [comment]
hey, thanks for the PR @djohal.
But the loader in this PR isn't as per the loader we have in the designs.
would you be able to modify this to use the one we have in our designs?
image
The above image represents the loader animation required. The orange icon remains as it is, while the red dots keep spinning.
I am attaching the necessary assets you will require as attachments to this comment

[loaderAssets-20200510T000436Z-001.zip](https://github.com/reach4help/reach4help/files/4604922/loaderAssets-20200510T000436Z-001.zip)

**Comment by jagoyette** [comment]
@djohal Have you made any progress on this PR? 

Animating the circles along the background square may be difficult with a package like Ant design. I took a crack at this using the SVG asset files that @ashwinkjoseph uploaded. I manipulated the SVG and added an animateMotion tag to each "circle". Take a look at the attached SVG file. Maybe you can integrate this into your solution and see if it is what the designers are looking for.

[Loading Logo.zip](https://github.com/reach4help/reach4help/files/4607457/Loading.Logo.zip)

**Comment by djohal** [comment]
> @djohal Have you made any progress on this PR?
> 
> Animating the circles along the background square may be difficult with a package like Ant design. I took a crack at this using the SVG asset files that @ashwinkjoseph uploaded. I manipulated the SVG and added an animateMotion tag to each "circle". Take a look at the attached SVG file. Maybe you can integrate this into your solution and see if it is what the designers are looking for.
> 
> [Loading Logo.zip](https://github.com/reach4help/reach4help/files/4607457/Loading.Logo.zip)

This looks really good! Thank you. I'll check with the designer to see if this works for her.

**Comment by jagoyette** [comment]
@djohal Attached is an updated SVG file with the proper gradient applied to the logo. Let me know if you need anything else or if you would like help integrating this into the loading screen.

[loading_logo.zip](https://github.com/reach4help/reach4help/files/4612788/loading_logo.zip)

**Pull request merged**
