### PR TITLE
[SHAYAN - REVIEW YOUR COMMENTS AND DECIDE WHAT TO DO] feat: reac-69 and reac-70. Implemented the rest of the about page

### PR DESCRIPTION
**Pull request by 14ssharp**
## Description

Finished up working on the about page. The pictures are all just from the github contributors, so I am sure there will be a lot of changes still needed there. I have made structured this in a way that shouldn't be too hard to edit. The image sources are in contributors.tsx, which is imported into AboutPage.tsx. You can change a picture by editing one of those image sources.

## Motivation

Reac-69 and Reac-70

## Testing Guidelines

1) Run the development server
2) Visually confirm the webpage layout

## Release Checklist

- [ ] This code has unit tests
- [ ] I have a plan to verify that these changes are working as expected after deploy
- [ ] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected

## Security Checklist

This PR creates, modifies, or deletes:

- [ ] API routes: API routes, parameters, or user authorization
- [ ] Authentication: Authentication mechanism
- [ ] Credentials: Server side credentials, or secrets in configuration / source code
- [ ] Cryptography: Encryption, hashing, certificates, signatures, random numbers, etc.
- [ ] User data: personal information handling, logs, error messages, etc.

## Additional Notes
image
image

### CODE REVIEW

**Review by ashwinkjoseph — CHANGES_REQUESTED** [review]
Hey, the PR looks good to me, but could you retrieve the user list from https://github.com/reach4help/reach4help/blob/development/.all-contributorsrc instead of keeping it as a static file?

I have requested this as a change in this review, but if you want I can merge this in and accept the change as a new PR. If this is what you want, let me know by commenting here and mentioning me or by messaging me on slack

**Comment by schowdhury8** [comment]
On that note, @all-contributors please add @14ssharp for code

**Comment by schowdhury8** [comment]
Actually, on second thought @ashwinkjoseph , all-contributors doesn't usually represent the designers, marketers or product owners. So I think a separate file isn't a bad idea, as it'll give us a bit more flexibility to convey other information like titles and whatnot. 
@14ssharp would you be able to make your list of people similar to something like this instead: https://github.com/reach4help/reach4help/blob/526636ba15e0e55648652ee389341c84e1cabb9f/site/src/sections/team/index.js#L9
It'll also save you time from trying to hardcode each person cuz you can just map through 'em.

**Comment by ashwinkjoseph** [comment]
> Actually, on second thought @ashwinkjoseph , all-contributors doesn't usually represent the designers, marketers or product owners. So I think a separate file isn't a bad idea, as it'll give us a bit more flexibility to convey other information like titles and whatnot.
> @14ssharp would you be able to make your list of people similar to something like this instead:
> 
> https://github.com/reach4help/reach4help/blob/526636ba15e0e55648652ee389341c84e1cabb9f/site/src/sections/team/index.js#L9-L30
> 
> 
> It'll also save you time from trying to hardcode each person cuz you can just map through 'em like this:
> https://github.com/reach4help/reach4help/blob/526636ba15e0e55648652ee389341c84e1cabb9f/site/src/sections/team/index.js#L63-L68

Yea, that sounds good too, if we are okay with managing that list separately, but it shouldn't be too hard considering it's JSON now

**Pull request closed without merging**
