### PR TITLE
Feature/762 signup redesign

### PR DESCRIPTION
**Pull request by mcverter**
https://github.com/reach4help/reach4help/issues/762

This should be merged.  Bug is out of date and should be closed with this PR.
Auth screens are done.
Language functionality should be reviewed by @ashwinkjoseph 

Language Fixes do seem to work but it looks weird because we do not have translations yet.
When you change language, app reloads to introduction.  This page should be displayed in the new language but we don't yet have the translatons for this.  You can see it is working by checking the Facebook button label on the last screen

### CODE REVIEW

**Comment by mcverter** [comment]
@ashwinkjoseph Please review
https://github.com/mcverter/reach4help/blob/feature/762-signup-redesign/web-client/src/translations/i18n.ts#L16
https://github.com/mcverter/reach4help/blob/feature/762-signup-redesign/web-client/src/modules/registration/components/RegistrationSteps/Step1_SelectLanguage.tsx#L28

I tried init() and changeLanguage().  Not sure how well either works.  Need to test

**Comment by mcverter** [comment]
@sabind @ashwinkjoseph don't merge yet.  a few minor changes

**Comment by mcverter** [comment]
@sabind @ashwinkjoseph ready to merge

**Comment by mcverter** [comment]
AUTH_STEP_1
AUTH_STEP_2
AUTH_STEP_3
AUTH_STEP_4_POPUP
AUTH_STEP_4

**Comment by ashwinkjoseph** [comment]
@mcverter, looking at your commits, are you allowing the hooks? why is it that your commit messages don't comply with the hooks?

**Comment by ashwinkjoseph** [comment]
@mcverter This PR looks really good, but I feel it's more oriented towards desktops. I would prefer to have lesser screens and steps in a mobile version.
I think we should keep this PR as it is.
We will be starting development on desktop screens very soon. 
When we do, I think this PR would make a very valuable contribution at the time and we will ask the Design team to attributes from this for the desktop version of the sign-up screen.

**Comment by mcverter** [comment]
dev is blocked until this is merged @ashwinkjoseph

**Comment by mcverter** [comment]
@ashwinkjoseph you can merge this now.  signup is now a 2-page process:  welcome/language and email
language/welcome is fixed but  we are not getting translated template strings -- even though you can see the google and faisbuuk buttons are translated.

the rest of the screens require more work than anticipated because the header changes between screens.

**Comment by ashwinkjoseph** [comment]
> @ashwinkjoseph you can merge this now. signup is now a 2-page process: welcome/language and email
> language/welcome is fixed but we are not getting translated template strings -- even though you can see the google and faisbuuk buttons are translated.
> 
> the rest of the screens require more work than anticipated because the header changes between screens.

Okay, I will look into this and fix it as soon as I can merge this.

**Pull request merged**
