### PR TITLE
Improvements to ZenHub issue sync

### PR DESCRIPTION
**Pull request by s0**
## Description

* Include which epics an issue is part of
* Remove some spurious curly braces

### CODE REVIEW

**Comment by ashwinkjoseph** [comment]
> I have a question regarding these variable names (e, e_1, e_2, etc). Do you think that this can hinder future collab on this particular service or is it okay to leave it like this? I find it a little difficult to understand what it represents. But other than that it looks good to me!

Hey, are you checking the compiled .js or are you checking the .ts file?

**Comment by s0** [comment]
Yeah that's just the compiled JS, it needs to be checked in because it's running as a github action :)

**Comment by s0** [comment]
> I have a question regarding these variable names (e, e_1, e_2, etc). Do you think that this can hinder future collab on this particular service or is it okay to leave it like this? I find it a little difficult to understand what it represents. But other than that it looks good to me!

**Comment by puzzledbytheweb** [comment]
> > I have a question regarding these variable names (e, e_1, e_2, etc). Do you think that this can hinder future collab on this particular service or is it okay to leave it like this? I find it a little difficult to understand what it represents. But other than that it looks good to me!
> 
> Yeah that's just the compiled JS, it needs to be checked in because it's running as a github action :)

Ah thanks, was not understanding that ;)

**Pull request merged**
