### PR TITLE
feat(site): fix .well-known/security.txt

### PR DESCRIPTION
**Pull request by s0**
Description
-----------

Fixes deployment of `.well-known` file: #190 

Motivation
----------

Testing Guidelines
------------------

Release Checklist
-----------------

- [ ] This code has unit tests
- [ ] I have a plan to verify that these changes are working as expected after deploy
- [ ] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected

Security Checklist
-------------------

This PR creates, modifies, or deletes:

- [ ] API routes: API routes, parameters, or user authorization
- [ ] Authentication: Authentication mechanism
- [ ] Credentials: Server side credentials, or secrets in configuration / source code
- [ ] Cryptography: Encryption, hashing, certificates, signatures, random numbers, etc.
- [ ] User data: personal information handling, logs, error messages, etc.

Additional Notes
----------------

### CODE REVIEW

**Comment by s0** [comment]
Hmm, doesn't seem to work...: https://deploy-preview-207--reach4help.netlify.com/.well-known/security.txt

**Comment by s0** [comment]
It is visible here though: https://deploy-preview-207--reach4help.netlify.com/well-known/security.txt

hmm, @luisFilipePT any ideas?

**Comment by mdmfernandes** [comment]
@s0 not sure about this, but I think that you need to put the _redirects file on the static folder, so that when you build gatsby, the file will be located at the public directory (i.e. public/_redirects)

**Comment by luisFilipePT** [comment]
@s0 Sorry for the late response, first time I am hearing about this `security.txt` 😊 . But from what I could gather, and I have not tested it, why simply not add it to the static folder and to the root of the repo? (yes keep duplicate files)
From what I read here (https://securitytxt.org/):
* `It can also be placed in the root directory (/security.txt) of a website`
* For code repositories, the file should be placed in the root directory of the repository.

🤔 

Out of curiosity, is this widely used?

**Comment by s0** [comment]
> @s0 Sorry for the late response, first time I am hearing about this `security.txt`  . But from what I could gather, and I have not tested it, why simply not add it to the static folder and to the root of the repo? (yes keep duplicate files)
> From what I read here (https://securitytxt.org/):
> 
> * `It can also be placed in the root directory (/security.txt) of a website`
> * `For code repositories, the file should be placed in the root directory of the repository.`

Good shout, didn't look closely enough to see we could place it at root, i'll try moving the redirects, and if that doesn't work i'll move it to root. In any case duplicating it to the root of the repo is a good idea!

> 
> Out of curiosity, is this widely used?

It's a relatively new standard, so no not yet, but it's well-known within the security industry ;)

**Comment by s0** [comment]
Actually we already have a `SECURITY.md` in the root of the repo which integrates with GitHub's security features, so i think duplicating the `txt` file in the root of the repo too is unnecessary.

**Comment by s0** [comment]
Looks like moving it to public dir worked, thanks @mdmfernandes: https://deploy-preview-207--reach4help.netlify.com/.well-known/security.txt

**Comment by s0** [comment]
This is ready to be merged again now with someone's approval.

**Pull request merged**
