### PR TITLE
PR template

### PR DESCRIPTION
**Pull request by mdeous**
Provides a pull-request template to devs and contributors,

### CODE REVIEW

**Comment by micaelr95** [comment]
I also think the keyword `closes` and a link for the issue the PR closes is important

**Comment by sabind** [comment]
> Would actually have a section to reference issues or indicate the closes keyword, to link PR to issue in project board

I think GH has changed that UI now to where you link issues on the right hand side where you can select milestones and stuff?

**Comment by mdeous** [comment]
Added instructions to close or reference related issue.

**Comment by sabind** [comment]
> Added instructions to close or reference related issue.

clean solution 👍

**Comment by micaelr95** [comment]
@all-contributors please add @s0 for ideas.

**Comment by micaelr95** [comment]
@all-contributors please add @micaelr95 for ideas.

**Comment by micaelr95** [comment]
@all-contributors please add @micaelr95 for ideas.

**Pull request merged**
