### PR TITLE
Added Map Models to Back End

### PR DESCRIPTION
**Pull request by sabind**
## Description

- Add markers to the functions codebase
- Fixes bugs in model `toObject` functions that impact firestore conversions.

## Motivation

start preparing the backend for tracking markers

## Release Checklist

- [ ] This code has unit tests
- [ ] I have a plan to verify that these changes are working as expected after deploy
- [ ] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected

## Security Checklist

This PR creates, modifies, or deletes:

- [ ] API routes: API routes, parameters, or user authorization
- [ ] Authentication: Authentication mechanism
- [ ] Credentials: Server side credentials, or secrets in configuration / source code
- [ ] Cryptography: Encryption, hashing, certificates, signatures, random numbers, etc.
- [ ] User data: personal information handling, logs, error messages, etc.

### CODE REVIEW

**Comment by s0** [comment]
Before we can get this in, we should decide on: #414

**Comment by sabind** [comment]
Now that the models in the front end are merged, I’ll deal with this over the weekend as well as the login bits for custom claims.

**Comment by sabind** [comment]
@s0 Updated the models on the Map and Backend to align them

**Comment by s0** [comment]
I'll try to review this today :)

**Pull request merged**
